name: status check compile (does not push)
"on":
  push:
    branches-ignore: [master, main]
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Compile
        uses: EagleoutIce/tikzpingus/.github/workflows/unify-doc-compile.yaml@main
      - uses: actions/upload-artifact@v3
        with:
          name: status-artifact
          path: |
            build/*.pdf
            build/documentation.log
            build/documentation.aux
            build/documentation.ilg
            build/documentation.ind
            build/documentation.idx
