name: unified documentation compile
"on":
  workflow_run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      # https://github.com/actions/cache/issues/342
      - name: 💾 Caching
        uses: actions/cache@v3
        with:
          path: |
            build
            sub_*
          key: ${{ runner.os }}-pengu-cache-doc-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-pengu-cache-doc-
      - name: 📄 Compile the Documentation, showcase and minimal
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            doc/tikzpingus-doc.tex
            examples/showcase.tex
            examples/minimal.tex